version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt "+ test:compile"
      - save_cache:
          paths:
            - "~/.ivy2"
            - "~/.sbt"
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: sbt "+ test"
